### ISSUE TITLE
PhantomJS error

### ISSUE THREAD

**Issue by montogeek** [lucasfeliciano/fetch-everywhere#4]
Hi!

In a PhantomJS environment this error raises:
`not ok 229 PhantomJS 1.9 - Global error: TypeError: 'undefined' is not a function (evaluating 'globalObj.fetch.bind(globalObj)')`

I guess `self` does not exists in PhantomJS

**Comment by lucasfeliciano** [comment]
This should be fixed with #3

**Comment by lucasfeliciano** [comment]
I'm making a release now.
If the error persist let me know

**Comment by montogeek** [comment]
@lucasfeliciano The error is still happening
I am search for global variables in PhantomJS but I can't find docs about it

**Comment by lucasfeliciano** [comment]
Is #2 fixed for you?

I'll investigate about the phantomJS environment

**Comment by montogeek** [comment]
Yes #2 is fixed :) Thanks!
